### ISSUE TITLE
Help request (PyUSB problems?) w/ HX1K board

### ISSUE THREAD

**Issue by rnjacobs** [davidcarne/iceBurn#1]
Sorry about filing this as an "issue" ... I have no idea how else to do this.

I bought a HX1K based board and ... I'll omit the backstory.
Anyway, I'm using HEAD from both your repository and walac's pyusb repository, and on a freshly-inserted device I see the following:

$ ./regtool.py 
Traceback (most recent call last):
  File "./regtool.py", line 31, in <module>
    main()
  File "./regtool.py", line 20, in main
    for atype, arg in args.actions:
TypeError: 'NoneType' object is not iterable
$ ./regtool.py 
Traceback (most recent call last):
  File "./regtool.py", line 31, in <module>
    main()
  File "./regtool.py", line 20, in main
    for atype, arg in args.actions:
TypeError: 'NoneType' object is not iterable
$ ./iCEburn.py
$ ./iCEburn.py
Traceback (most recent call last):
  File "./iCEburn.py", line 75, in <module>
    main()
  File "./iCEburn.py", line 20, in main
    with board.get_gpio() as gpio:
  File "/home/rjacobs/src/iceBurn/libiceblink.py", line 149, in **enter**
    self.open()
  File "/home/rjacobs/src/iceBurn/libiceblink.py", line 161, in open
    self.dev.checked_cmd(0x03, 0x00, "gpioopen", [0x00], noret=True)
  File "/home/rjacobs/src/iceBurn/libiceblink.py", line 339, in checked_cmd
    status, respl = self.cmd(cmd, subcmd, payload, ressize, show)
  File "/home/rjacobs/src/iceBurn/libiceblink.py", line 349, in cmd
    ressize)
  File "/home/rjacobs/src/iceBurn/libiceblink.py", line 362, in cmd_i
    res = bytes(self.ep_cmdin.read(result_size))
  File "/usr/local/lib/python3.4/dist-packages/usb/core.py", line 364, in read
    return self.device.read(self, size_or_buffer, timeout)
  File "/usr/local/lib/python3.4/dist-packages/usb/core.py", line 918, in read
    self.__get_timeout(timeout))
  File "/usr/local/lib/python3.4/dist-packages/usb/backend/libusb0.py", line 489, in bulk_read
    timeout)
  File "/usr/local/lib/python3.4/dist-packages/usb/backend/libusb0.py", line 562, in __read
    timeout
  File "/usr/local/lib/python3.4/dist-packages/usb/backend/libusb0.py", line 380, in _check
    raise USBError(errmsg, ret)
usb.core.USBError: [Errno None] b'No error'

Subsequent execution of either iCEburn or regtool return the final longest backtrace.

Help?

**Comment by davidcarne** [comment]
This is probably so late a reply as to be useless - sorry for the late response.

./regtool.py needs to be used with either a -r or -w flag to tell it to do something. I should probably make a useful error message.

With iCEburn.py, I seem to recall that occurring when the chip gets into an inconsistent state. Unfortunately I don't have either of my iCE40 boards around to check right now. If you are still dealing with this / can repro it, ping me and I'll try and troubleshoot it.

**Comment by rnjacobs** [comment]
I'm afraid that I didn't even notice this for ten months. Sorry!

Anyway, I do still have the iCE40HX board and can reproduce:
$ ./regtool.py -r 0
Traceback (most recent call last):
  File "./regtool.py", line 31, in <module>
    main()
  File "./regtool.py", line 23, in main
    print("READ  %02x: %02x" % (addr, comm.readReg(addr)))
  File "/home/rjacobs/src/iceBurn/libiceblink.py", line 124, in readReg
    0x01, 0x00, 0x00, 0x0])
  File "/home/rjacobs/src/iceBurn/libiceblink.py", line 341, in checked_cmd
    raise SPIProtocolError(name, status)
libiceblink.SPIProtocolError: Command bcommsetval failed with error: error code 5

The iCEburn backtrace is unchanged.
